# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "data-builder"
client_id = "ada2bcdc0952aa8f9cde056eb1be2766"
application_url = "https://citizen-lights-strongly-dominican.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_publications,read_customers,write_customers,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,read_inventory,write_inventory,read_marketing_events,read_orders,write_orders,read_payment_terms,read_product_listings,write_publications,read_resource_feedbacks,read_reports,read_returns,read_assigned_fulfillment_orders,read_cart_transforms,read_checkouts,read_content,write_content,read_customer_merge,write_customer_merge,read_third_party_fulfillment_orders,read_order_edits,read_shopify_payments_payouts"

[auth]
redirect_urls = [
  "https://citizen-lights-strongly-dominican.trycloudflare.com/auth/callback",
  "https://citizen-lights-strongly-dominican.trycloudflare.com/auth/shopify/callback",
  "https://citizen-lights-strongly-dominican.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vibe-app.myshopify.com"
