export const dataSearch = [
  { value: "product", label: "Product" },
  { value: "customer", label: "Customer" },
  { value: "tag_collection", label: "Tag And Collection" },
  { value: "fullfill_shipping", label: "Fullfillment And Shipping" },
  { value: "sales_order", label: "Sales And Order" },
  { value: "inventory", label: "Inventory" },
  { value: "tax", label: "Tax" },
  { value: "transition", label: "Transition" },
  { value: "payout", label: "Shopify Payment And Payout" },
];

export const dataTitleReport = [
  { value: "own", label: "My Report" },
  { value: "product", label: "Product Report" },
  { value: "customer", label: "Customer Report" },
  { value: "tag_collection", label: "Tag And Collection" },
  { value: "fullfill_shipping", label: "Fullfillment And Shipping" },
  { value: "sales_order", label: "Sales And Order" },
  { value: "inventory", label: "Inventory Report" },
  { value: "tax", label: "Tax Report" },
  { value: "transition", label: "Transition Report" },
  { value: "payout", label: "Shopify Payment And Payout" },
];

export const defaultPopoverProduct = {
  title: false,
  bodyHtml: false,
  vendor: false,
  productType: false,
  createdAt: false,
  handle: false,
  updatedAt: false,
  publishedAt: false,
  status: false,
  totalInventory: false,
  description: false,
  publicationCount: false,
  onlineStoreUrl: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
  // title: false,
};

export const defaultHeadingProduct = {
  title: "Product title",
  bodyHtml: "Body HTML",
  vendor: "Product vendor",
  productType: "Product type",
  createdAt: "Create at",
  handle: "Product handle",
  updatedAt: "Update at",
  publishedAt: "Publish at",
  status: "Product status",
  totalInventory: "Inventory",
  description: "Description",
  publicationCount: "Publication count",
  onlineStoreUrl: "Online store url",
};
